### ISSUE TITLE
New feature: Hardware Acceleration

### ISSUE THREAD

**Issue by MartinKuhl** [mdvorak/ha-addon-jellyfin#25]
Is there a way to determine on which plattform jellyfin is running so that your are able to enable the hardware acceleration?
https://hub.docker.com/r/linuxserver/jellyfin

I am running jellyfin direcly via docker run and using the following device tags to enable hardware acceleration on my Pi4:

```
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12 
```

**Comment by mdvorak** [comment]
I think that this should be doable if it would support custom config options and volumes, I'll take a look.

**Comment by Antexa** [comment]
Could be great to get this on your add-on @mdvorak 

BTW works like a charm on armv7 (Compute Module 4)

**Comment by mdvorak** [comment]
I've added `video: true`, but I don't have a way to test what it actually does. It might mount proper devices automatically (or not), please let me know if it works.

**Comment by mdvorak** [comment]
I've looked into what is needed to enable it directly in Jellyfin, and there is a reason why Jellyfin itself does not do any auto-detection - it is problematic.
So automatic configuration of Jellyfin won't be possible. You have to enable it in the administration yourself.

Still, let me know if video mounting by HA helped somehow, thanks.

**Comment by Antexa** [comment]
I gave a quick try this morning but I don't know how to start for debugging this. 

(My browser is setup in French and I can't setup English language on Jellyfin configuration page...)
<img width="894" alt="image" src="https://user-images.githubusercontent.com/8592053/213868445-b15bd22b-fcc2-4a24-9be3-4b13333b4061.png">

I gave a try on Safari with a movie and nothing appears, the CPU didn't spike at all either.

Maybe @MartinKuhl will have better result ?

**Comment by MartinKuhl** [comment]
I will test in the next couple of days. @Antexa can you check your transcoding log if there is any sign of hardware transcoding?

**Comment by Antexa** [comment]
I got this on the "FFmpeg.Transcode" log file

```
Press [q] to stop, [?] for help
[h264_v4l2m2m @ 0x5594d495b0] Using device /dev/video11
[h264_v4l2m2m @ 0x5594d495b0] driver 'bcm2835-codec' on card 'bcm2835-codec-encode' in mplane mode
[h264_v4l2m2m @ 0x5594d495b0] requesting formats: output=YU12 capture=H264
[h264_v4l2m2m @ 0x5594d495b0] capture VIDIOC_REQBUFS failed: Cannot allocate memory
[h264_v4l2m2m @ 0x5594d495b0] no v4l2 capture context's buffers
[h264_v4l2m2m @ 0x5594d495b0] can't configure encoder
[h264_v4l2m2m @ 0x5594d495b0] V4L2 failed to unmap the output buffers
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

**Comment by MartinKuhl** [comment]
There anyway to connect jellyfin with a SMB share protected an authentification? 
With my docker version I used the following approach via s6-overlay: [](https://github.com/mrvnklm/plex-docker-smb-mount)

**Comment by MartinKuhl** [comment]
For every solution I found, I need the --privileged flag set and the cifs-utils package installed within the container.

**Comment by mdvorak** [comment]
Yes, that is pretty much true. Thats why I'm not very fond of adding this. It belongs on the host, but I also know there are open unresolved feature requests on HA.
Please open new issue for this, so we can continue the discussion there.

**Comment by MartinKuhl** [comment]
https://github.com/home-assistant/core/issues/87286

**Comment by MartinKuhl** [comment]
I think I will create my own jellyfin docker and will go this approach: https://github.com/mrvnklm/plex-docker-smb-mount 
So I use the cifs command and mount my NAS smb share direcly within the jellyfin docker.
I don't think that a general option to mount SMB share via HA will come soon.

**Comment by twosky2000** [comment]
I have added ``` --gpus all ``` to my container for my Nvidia GTX 970.
h264 does not work jet, but seams to work.


```
sudo docker inspect   --format "$(curl -s https://gist.githubusercontent.com/efrecon/8ce9c75d518b6eb863f667442d7bc679/raw/run.tpl)"  addon_3ce0ef5e_jellyfinserver
docker run \
  --name "/addon_3ce0ef5e_jellyfinserver" \
  --runtime "runc" \
  --mount type=bind,source=/dev,destination=/dev,readonly \
  --mount type=bind,source=/usr/share/hassio/addons/data/3ce0ef5e_jellyfinserver,destination=/data \
  --mount type=bind,source=/usr/share/hassio/homeassistant,destination=/config \
  --mount type=bind,source=/usr/share/hassio/ssl,destination=/ssl,readonly \
  --mount type=bind,source=/usr/share/hassio/share,destination=/share,bind-propagation=rslave \
  --mount type=bind,source=/usr/share/hassio/media,destination=/media,bind-propagation=rslave \
  --log-driver "journald" \
  --log-opt tag="{{.Name}}" \
  --restart "" \
  --add-host "hassio:172.30.32.2" \
  --add-host "supervisor:172.30.32.2" \
  --publish "0.0.0.0:8096:8096/tcp" \
  --network "hassio" \
  --network-alias "3ce0ef5e-jellyfinserver" \
  --network-alias "25b776270c8c" \
  --hostname "3ce0ef5e-jellyfinserver" \
  --domainname "local.hass.io" \
  --expose "8096/tcp" \
  --env "TZ=Europe/Zurich" \
  --env "SUPERVISOR_TOKEN=************************************" \
  --env "HASSIO_TOKEN=*************************************" \
  --env "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
  --env "HEALTHCHECK_URL=http://localhost:8096/health" \
  --env "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1" \
  --env "LC_ALL=en_US.UTF-8" \
  --env "LANG=en_US.UTF-8" \
  --env "LANGUAGE=en_US:en" \
  --env "JELLYFIN_DATA_DIR=/share/jellyfin" \
  --env "JELLYFIN_CACHE_DIR=/share/jellyfin/cache" \
  --env "JELLYFIN_CONFIG_DIR=/share/jellyfin/config" \
  --env "JELLYFIN_LOG_DIR=/config/log" \
  --env "JELLYFIN_WEB_DIR=/jellyfin/jellyfin-web" \
  --env "JELLYFIN_FFMPEG=/usr/lib/jellyfin-ffmpeg/ffmpeg" \
  --env "NVIDIA_VISIBLE_DEVICES=all" \
  --env "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility" \
  --gpus all \
  --label "io.hass.arch"="amd64" \
  --label "io.hass.description"="Jellyfin Server add-on" \
  --label "io.hass.name"="Jellyfin Server" \
  --label "io.hass.type"="addon" \
  --label "io.hass.url"="https://github.com/mdvorak/ha-addon-jellyfin" \
  --label "io.hass.version"="1.1.2" \
  --label "org.opencontainers.image.created"="2023-04-23 19:53:08+00:00" \
  --label "org.opencontainers.image.version"="1.1.2" \
  --label "supervisor_managed"="" \
  --detach \
  --entrypoint "./jellyfin/jellyfin" \
```

**Comment by ignacio82** [comment]
Any updates? I'm trying to decide whether to go with home assistant os or something else and this is a critical factor.

**Comment by mdvorak** [comment]
@ignacio82 What HW are you trying to run it on? I don't have much options where to test HW accel on HA, I'm running it in VM on server without GPUs..

**Comment by MartinKuhl** [comment]
Hi all, for a long time I was able to look into this topic agin. Thanks @mdvorak in the transcode log I found:

Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_v4l2m2m))
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[h264_v4l2m2m @ 0x55a0ec2370] Using device /dev/video11
[h264_v4l2m2m @ 0x55a0ec2370] driver 'bcm2835-codec' on card 'bcm2835-codec-encode' in mplane mode
[h264_v4l2m2m @ 0x55a0ec2370] requesting formats: output=YU12 capture=H264

I would say hardware acceleration is working.
Together with the network storage feature (https://www.home-assistant.io/common-tasks/os/#network-storage) I can now use this jellyfin addon out-of-the-box. 

Thanks a lot
