### ISSUE TITLE
Feature request : access NFS mounted in /media

### ISSUE THREAD

**Issue by cybertorture** [mdvorak/ha-addon-jellyfin#41]
Hello,
I managed to mount my media over NFS inside HA. The issue is that media browser in HA is working and accessing everything, but Jellyfin addon does not see the files.

is there something i miised ?

**Comment by mdvorak** [comment]
HA now supports mounting media volumes directly, so this feature should not be needed. Just mount NFS to media and it should be accessible by Jellyfin.
