### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Mis1ify** [mdvorak/ha-addon-jellyfin#49]
Hi, is it possible to migrate to new version of Jellyfin?

**Comment by mdvorak** [comment]
Working on it

**Comment by mdvorak** [comment]
Sorry for the delay guys, its out with https://github.com/jellyfin/jellyfin/releases/tag/v10.8.13

**Comment by Mis1ify** [comment]
Thx so much!

**Comment by guykes83** [comment]
Great!
