### ISSUE TITLE
Host Networking

### ISSUE THREAD

**Issue by OtisPresley** [mdvorak/ha-addon-jellyfin#62]
Is it possible within the Home Assistant Environment to have an option for using Host Networking for this addon? The DLNA Server will not be discovered without the being exposed to the network where the the receivers are.

**Comment by OtisPresley** [comment]
Thanks @weidi

**Comment by mdvorak** [comment]
Released in https://github.com/mdvorak/ha-addon-jellyfin/pull/69
You need to uninstall current install, and install variant with Host Network from Add-on store
